<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches [
    <!ELEMENT coches (fabricantes, modelos, premios)>

    <!ELEMENT fabricantes (fabricante)+>
    <!ELEMENT fabricante (fundador, fundacion, pais)>
    <!ATTLIST fabricante id ID #REQUIRED>
    <!ELEMENT fundador (#PCDATA)>
    <!ELEMENT fundacion EMPTY>
    <!ATTLIST fundacion año CDATA #REQUIRED>
    <!ELEMENT pais (#PCDATA)>

    <!ELEMENT modelos (modelo)+>
    <!ELEMENT modelo (nombre, segmento, inicio)>
    <!ATTLIST modelo fabricante CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT segmento (#PCDATA)>
    <!ELEMENT inicio EMPTY>
    <!ATTLIST inicio año CDATA #REQUIRED>

    <!ELEMENT premios (premio)+>
    <!ELEMENT premio EMPTY>
    <!ATTLIST premio nombre CDATA #REQUIRED>
    <!ATTLIST premio año CDATA #REQUIRED>
    <!ATTLIST premio modelo CDATA #REQUIRED>
]>

<coches>
    <fabricantes>
        <fabricante id="Peugeot">
            <fundador>Armand Peugeot</fundador>
            <fundacion año="1882" />
            <pais>Francia</pais>
        </fabricante>
        <fabricante id="Renault">
            <fundador>Louis Renault</fundador>
            <fundacion año="1899" />
            <pais>Francia</pais>
        </fabricante>
        <fabricante id="Opel">
            <fundador>Adam Opel</fundador>
            <fundacion año="1862" />
            <pais>Alemania</pais>
        </fabricante>
        <fabricante id="Volkswagen">
            <fundador>Deutsche Arbeitsfront</fundador>
            <fundacion año="1937" />
            <pais>Alemania</pais>
        </fabricante>
    </fabricantes>

    <modelos>
        <modelo fabricante="Peugeot">
            <nombre>Peugeot 308</nombre>
            <segmento>C</segmento>
            <inicio año="2007" />
        </modelo>
        <modelo fabricante="Opel">
            <nombre>Opel Astra</nombre>
            <segmento>C</segmento>
            <inicio año="1991" />
        </modelo>
        <modelo fabricante="Volkswagen">
            <nombre>Volkswagen Passat</nombre>
            <segmento>D</segmento>
            <inicio año="1973" />
        </modelo>
        <modelo fabricante="Peugeot">
            <nombre>Peugeot 3008</nombre>
            <segmento>C</segmento>
            <inicio año="2007" />
        </modelo>
        <modelo fabricante="Volkswagen">
            <nombre>Volkswagen Golf</nombre>
            <segmento>C</segmento>
            <inicio año="2007" />
        </modelo>
    </modelos>

    <premios>
        <premio nombre="coche del año Europa" año="2017" modelo="Peugeot 3008" />
        <premio nombre="coche del año Europa" año="2016" modelo="Opel Astra" />
        <premio nombre="coche del año Europa" año="2015" modelo="Volkswagen Passat" />
        <premio nombre="coche del año Europa" año="2014" modelo="Peugeot 308" />
        <premio nombre="coche del año Europa" año="2013" modelo="Volkswagen Golf" />
    </premios>
</coches>