<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    El atributo kernel de lanzamiento no puede ser IDREF debido a que el atributo id de kernel no es de tipo ID.
    No podria ser de tipo ID ya que los ID deben comenzar con letra o guion bajo, y el valor de kernel es un numero.
    Para poder hacerlo deberiamos cambiar el atributo ID de kernel a tipo ID y cambiar los valores para que comienzen por letra.
-->
<!DOCTYPE software-libre [
    <!ELEMENT software-libre (lanzamientos, distribuciones, escritorios, kernels)>

    <!ELEMENT lanzamientos (lanzamiento)+>
    <!ELEMENT lanzamiento EMPTY>
    <!ATTLIST lanzamiento distribucion IDREF #REQUIRED >
    <!ATTLIST lanzamiento version CDATA #REQUIRED >
    <!ATTLIST lanzamiento año CDATA #REQUIRED >
    <!ATTLIST lanzamiento mes CDATA #REQUIRED >
    <!ATTLIST lanzamiento escritorio IDREF #REQUIRED >
    <!ATTLIST lanzamiento kernel IDREF #REQUIRED >

    <!ELEMENT distribuciones (distribucion)+>
    <!ELEMENT distribucion (nombre, web, nacimiento, derivada?)>
    <!ATTLIST distribucion id ID #REQUIRED >
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT web (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
    <!ELEMENT derivada (#PCDATA)>

    <!ELEMENT escritorios (escritorio)+>
    <!ELEMENT escritorio (nombre, web, nacimiento)>
    <!ATTLIST escritorio id ID #REQUIRED >

    <!ELEMENT kernels (kernel)+>
    <!ELEMENT kernel EMPTY>
    <!ATTLIST kernel id ID #REQUIRED>
    <!ATTLIST kernel año CDATA #REQUIRED>
    <!ATTLIST kernel mes CDATA #REQUIRED>
]>
<software-libre>

    <lanzamientos>
        <lanzamiento distribucion="manjaro" version="17.1" año="2017" mes="12" escritorio="xfce"
            kernel="V4.14" />
        <lanzamiento distribucion="mint" version="18.3" año="2017" mes="11" escritorio="cinnamon"
            kernel="V4.10" />
        <lanzamiento distribucion="mint" version="19" año="2018" mes="6" escritorio="cinnamon"
            kernel="V4.15" />
        <lanzamiento distribucion="ubuntu" version="17.10" año="2017" mes="10" escritorio="gnome"
            kernel="V4.13" />
        <lanzamiento distribucion="ubuntu" version="18.04" año="2018" mes="4" escritorio="gnome"
            kernel="V4.15" />
        <lanzamiento distribucion="debian" version="8" año="2015" mes="4" escritorio="gnome"
            kernel="V3.16" />
        <lanzamiento distribucion="debian" version="9" año="2017" mes="6" escritorio="gnome"
            kernel="V4.09" />
    </lanzamientos>

    <distribuciones>
        <distribucion id="manjaro">
            <nombre>Manjaro Linux</nombre>
            <web>https://manjaro.org/</web>
            <nacimiento>2011</nacimiento>
        </distribucion>
        <distribucion id="mint">
            <nombre>Linux Mint</nombre>
            <web>https://www.linuxmint.com/</web>
            <nacimiento>2006</nacimiento>
            <derivada>ubuntu</derivada>
        </distribucion>
        <distribucion id="ubuntu">
            <nombre>Ubuntu</nombre>
            <web>https://www.ubuntu.com/</web>
            <nacimiento>2004</nacimiento>
            <derivada>debian</derivada>
        </distribucion>
        <distribucion id="debian">
            <nombre>Debian GNU/Linux</nombre>
            <web>https://www.debian.org/</web>
            <nacimiento>1993</nacimiento>
        </distribucion>
    </distribuciones>

    <escritorios>
        <escritorio id="xfce">
            <nombre>XFCE</nombre>
            <web>https://xfce.org/</web>
            <nacimiento>1996</nacimiento>
        </escritorio>
        <escritorio id="kde">
            <nombre>KDE</nombre>
            <web>https://kde.org/</web>
            <nacimiento>1996</nacimiento>
        </escritorio>
        <escritorio id="gnome">
            <nombre>GNOME</nombre>
            <web>https://www.gnome.org/</web>
            <nacimiento>1999</nacimiento>
        </escritorio>
        <escritorio id="cinnamon">
            <nombre>Cinnamon</nombre>
            <web>https://cinnamon-spices.linuxmint.com/</web>
            <nacimiento>2011</nacimiento>
        </escritorio>
    </escritorios>

    <kernels>
        <kernel id="V4.15" año="2018" mes="1" />
        <kernel id="V4.14" año="2017" mes="11" />
        <kernel id="V4.13" año="2017" mes="9" />
        <kernel id="V4.10" año="2017" mes="2" />
        <kernel id="V4.09" año="2016" mes="12" />
        <kernel id="V3.16" año="2014" mes="8" />
    </kernels>

</software-libre>