<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [
    <!ELEMENT factura (emisor, cliente, detalle)>
    <!ATTLIST factura numero CDATA #REQUIRED>
    <!ATTLIST factura fecha CDATA #REQUIRED>

    <!ELEMENT emisor (nombre, cif, telefono)>
    <!ELEMENT cliente (nombre, cif, telefono)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cif (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>

    <!ELEMENT detalle (linea)+>
    <!ATTLIST detalle importe CDATA #REQUIRED>
    <!ELEMENT linea (descripcion, cantidad, oferta?, pvp)>
    <!ATTLIST linea codigo-articulo ID #REQUIRED>
    <!ATTLIST linea tipo (Libro | DVD | Varios) #IMPLIED>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT oferta EMPTY>
    <!ELEMENT pvp (#PCDATA)>
]>
<factura numero="27" fecha="18/12/2013">
    
    <emisor>
        <nombre>Librería Pérez</nombre>
        <cif>44555666B</cif>
        <telefono>777888999</telefono>
    </emisor>

    <cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <cif>33111222A</cif>
        <telefono>333999444</telefono>
    </cliente>

    <detalle importe="300">
        <linea codigo-articulo="AW7" tipo="Libro">
            <descripcion>Analítica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta />
            <pvp>25</pvp>
        </linea>
        <linea codigo-articulo="CP5" tipo="DVD">
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <pvp>30</pvp>
        </linea>
    </detalle>

</factura>