=== olixva/LenguajeMarcas_XML/xml + xsd/algo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definición del elemento principal "algo" -->
  <xs:element name="algo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fragil_00" maxOccurs="unbounded" /><!-- al no llevar type podría ser
        cualquier cosa y no se valida  -->
        <xs:element name="fragil_01" minOccurs="0" maxOccurs="unbounded" /><!-- Opcional -->

        <xs:element name="fragil_02" maxOccurs="unbounded"><!-- el type se define justo debajo -->
          <xs:simpleType><!-- simpleType por no tener hijos, ya que solo afecta al TYPE de contenido
            del elemento-->
            <xs:restriction base="xs:string">
              <xs:maxLength value="0" /><!-- Longitud 0 para que no se pueda incluir nada de
              texto-->
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="fragil_02bis" maxOccurs="unbounded"><!-- el type se define justo debajo -->
          <xs:complexType><!-- Al definirlo como complexType sin nada dentro, será un elemento vacío
            OBLIGATORIO (ni texto, ni hijos)-->
            <!-- Los complexType se pueden definir vacíos, no así los simpleType que han de tener
            definición -->
          </xs:complexType>
        </xs:element>

        <xs:element name="fragil_03" type="cadenaVacia" minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="fragil_03bis" type="cadenaVaciabis" minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="fragil_04">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="1" />
              <xs:maxLength value="10" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>


        <xs:element name="fragil_05" maxOccurs="unbounded"> <!-- el type no está escrito en esta
          línea de definición del elemento-->
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="cristal" />
              <xs:enumeration value="medicinas" />
              <xs:enumeration value="ceramica" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="fragil_06" minOccurs="0" maxOccurs="unbounded"><!-- Defino debajo el tipo
          de elemento-->
          <xs:complexType><!-- complexType por tener hijos o atributos -->
            <!-- los complexType hay que definirlos como: sequence, all, group, o mixed -->
            <!-- NO HAY CONTENIDO, no se define nada de contenido aquí -->
            <xs:sequence>
              <xs:element name="material">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="cristal" />
                    <xs:enumeration value="medicinas" />
                    <xs:enumeration value="ceramica" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="peso">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:totalDigits value="10" />
                    <xs:fractionDigits value="2" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="unidad_de_peso">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="kg" />
                    <xs:enumeration value="libras" />
                    <xs:enumeration value="onza" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="fragil_07" minOccurs="0" maxOccurs="unbounded"><!-- Defino debajo el tipo
          de elemento-->
          <xs:complexType mixed="true"><!-- complexType por tener hijos o atributos, mixed permitirá
            escribir texto dentro del elemento fragil_07, pero no se valida ese texto -->
            <!-- los complexType hay que definirlos como: sequence, all, group,  o mixed -->
            <!-- Antes de definir los hijos, hay que definir cómo será el contenido del elemento -->
            <!-- En este ejemplo no se ha querido limitar el texto del elemento fragil_07 -->
            <xs:sequence>
              <xs:element name="material">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="cristal" />
                    <xs:enumeration value="medicinas" />
                    <xs:enumeration value="ceramica" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="peso">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:totalDigits value="10" />
                    <xs:fractionDigits value="2" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>

              <xs:element name="unidad_de_peso">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="kg" />
                    <xs:enumeration value="libras" />
                    <xs:enumeration value="onza" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="fragil_08" type="fragil_08_Type" minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="fragil_09" type="fragil_09_Type" minOccurs="0" maxOccurs="unbounded" />


        <!-- ELEMENTOS CON ATRIBUTOS -->

        <xs:element name="Afragil_00" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="Amaterial" default="cristal">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="(cristal|medicinas|ceramica)" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="Afragil_01" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="Amaterial" default="cristal">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="(cristal|medicinas|ceramica)" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="Afragil_02" maxOccurs="unbounded">
          <xs:complexType> <!--al
            llevar atributo ha de ser complexType, y los complexType no pueden llevar restricciones 
            <xs:restriction base="xs:string">
                <xs:maxLength value="0"/>
            </xs:restriction> -->
            <xs:attribute name="Amaterial" default="cristal">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(cristal|medicinas|ceramica)" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>

        <xs:element name="Afragil_02bis" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="Amaterial" default="cristal">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="(cristal|medicinas|ceramica)" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>


      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!-- DECLARACION DE TIPOS  -->
  <!-- ****************************************************** -->

  <xs:simpleType name="cadenaVacia"> <!-- simpleType NO PUEDE CONTENER simpleContent ni
    complexContent, solo puede contener: list, union y restriction -->
    <xs:restriction base="xs:string">
      <xs:maxLength value="0" />
    </xs:restriction>
  </xs:simpleType>

  <!-- ****************************************************** -->

  <xs:complexType name="cadenaVaciabis" /> <!-- complexType  SE PUEDE DEFINIR VACÍO -->

  <!-- ****************************************************** -->


  <xs:complexType name="cadenaConContenido">
    <xs:simpleContent>
      <xs:extension base="xs:string">
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- ****************************************************** -->

  <xs:complexType name="fragil_08_Type">
    <xs:sequence>
      <xs:element name="descripcion">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="VACUNAS" />
            <xs:enumeration value="VASIJA" />
            <xs:enumeration value="COPAS" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="material">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="cristal" />
            <xs:enumeration value="medicinas" />
            <xs:enumeration value="ceramica" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="peso">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:totalDigits value="10" />
            <xs:fractionDigits value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="unidad_de_peso">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="kg" />
            <xs:enumeration value="libras" />
            <xs:enumeration value="onza" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>

  </xs:complexType>

  <!-- ****************************************************** -->
  <xs:complexType name="fragil_09_Type">

  </xs:complexType>


  <!-- ****************************************************** -->


</xs:schema>

=== olixva/LenguajeMarcas_XML/xml + xsd/algo2.xml
<?xml version="1.0" encoding="UTF-8"?>
<algo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="algo2.xsd">
  <!-- Elemento contenido:cualquier texto o VACÍO (sin hijos), ocurrencia:OBLIGATORIA y multiples
  veces para poder repetir de varias formas -->
  <fragil_00>fccxcxxcx</fragil_00>
  <fragil_00 />

  <!-- Elemento contenido:cualquier texto o VACÍO (sin hijos), ocurrencia:OPCIONAL y multiples veces
  para poder repetir de varias formas -->
  <fragil_01>fgdfgdfg</fragil_01>
  <fragil_01 />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OBLIGATORIA y multiples veces
  para poder repetir de varias formas -->
  <fragil_02></fragil_02>
  <fragil_02 />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OBLIGATORIA y multiples veces
  para poder repetir de varias formas -->
  <fragil_02bis></fragil_02bis>
  <fragil_02bis />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OPCIONAL y multiples veces para
  poder repetir de varias formas -->
  <fragil_03></fragil_03>
  <fragil_03 />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OPCIONAL y multiples veces para
  poder repetir de varias formas -->
  <fragil_03bis></fragil_03bis>
  <fragil_03bis />

  <!-- Elemento contenido:TEXTO OBLIGATORIO CON RESTRICCIONES (longitud de texto limitada) (sin
  hijos), ocurrencia:OPCIONAL y ÚNICO -->
  <fragil_04>cristal</fragil_04>

  <!-- Elemento contenido:TEXTO OBLIGATORIO CON RESTRICCIONES (ENUMERADO DE TEXTO) (sin hijos),
  ocurrencia:OPCIONAL y multiples veces para poder repetir de varias formas -->
  <fragil_05>cristal</fragil_05>
  <fragil_05>medicinas</fragil_05>
  <fragil_05>ceramica</fragil_05>

  <!-- Elemento contenido: TEXTO VACIO obligatorio (CON HIJOS), ocurrencia:OPCIONAL y multiples
  veces para poder repetir de varias formas -->
  <fragil_06>
    <material>cristal</material>
    <peso>12.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_06>

  <fragil_06>
    <material>medicinas</material>
    <peso>1.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_06>

  <fragil_06>
    <material>ceramica</material>
    <peso>78.45</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_06>

  <!-- Elemento contenido: TEXTO opcional (CON HIJOS), ocurrencia:OPCIONAL y multiples veces para
  poder repetir de varias formas -->
  <fragil_07>COPAS <material>cristal</material>
    <peso>12.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_07>

  <fragil_07>VACUNAS <material>medicinas</material>
    <peso>1.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_07>

  <fragil_07>
    <material>ceramica</material>
    <peso>78.45</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_07>

  <fragil_07>texto.... <material>ceramica</material>
    <peso>78.45</peso> otro texto <unidad_de_peso>kg</unidad_de_peso>mucho
    mas texto </fragil_07>

  <!-- Como los tipos mixed="true" pueden tener muchas veces contenido dentro de todos los nodos, a
  su " múltiple contenido"
     no se le pueden poner restricciones.., las tendríamos que poner dentro de algún elemento simple-->


  <!-- Elemento contenido: TEXTO VACÍO (CON HIJOS), ocurrencia:OPCIONAL y multiples veces para poder
  repetir de varias formas -->

  <fragil_08>
    <descripcion>VACUNAS</descripcion>
    <material>medicinas</material>
    <peso>1.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_08>

  <fragil_08> <!-- hemos impedido que haya contenido en este elemento, en su caso se pondrá el texto
    dentro de <descripción> -->
    <descripcion>VACUNAS</descripcion>
    <material>medicinas</material>
    <peso>1.56</peso>
    <unidad_de_peso>kg</unidad_de_peso>
  </fragil_08>


  <!--   <fragil_09 Amaterial="cristal">COPAS</fragil_09>  -->

  <!-- ELEMENTOS CON ATRIBUTOS -->

  <!-- Elemento contenido:cualquier texto o VACÍO (sin hijos), ocurrencia:OBLIGATORIA y multiples
  veces para poder repetir de varias formas -->
  <Afragil_00 Amaterial="cristal">fsdfgdffsdf</Afragil_00>
  <Afragil_00 Amaterial="cristal" />

  <!-- Elemento contenido:cualquier texto o VACÍO (sin hijos), ocurrencia:OPCIONAL y multiples veces
  para poder repetir de varias formas -->
  <Afragil_01 Amaterial="cristal">fgdfgdfg</Afragil_01>
  <Afragil_01 Amaterial="cristal" />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OBLIGATORIA y multiples veces
  para poder repetir de varias formas -->
  <Afragil_02 Amaterial="cristal"></Afragil_02>
  <Afragil_02 Amaterial="cristal" />

  <!-- Elemento contenido:VACÍO obligatorio (sin hijos), ocurrencia:OBLIGATORIA y multiples veces
  para poder repetir de varias formas -->
  <Afragil_02bis Amaterial="cristal"></Afragil_02bis>
  <Afragil_02bis Amaterial="cristal" />


</algo>
