=== olixva/LenguajeMarcas_XML/xml + xsd/ejemplo1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="todoList">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="tarea" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="ordenante" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="dni" type="xs:NMTOKEN" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="posibles_ejecutores" type="xs:NMTOKENS" use="required"></xs:attribute>
                        <xs:attribute name="estado" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="No_iniciada"></xs:enumeration>
                                    <xs:enumeration value="iniciada"></xs:enumeration>
                                    <xs:enumeration value="En_proceso"></xs:enumeration>
                                    <xs:enumeration value="Finalizada"></xs:enumeration>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="fecha" type="xs:string" use="optional"></xs:attribute>
                        <xs:attribute name="fechaLimite" type="xs:string" use="optional"></xs:attribute>
                    </xs:complexType>
                </xs:element>

                <xs:element name="persona" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="dni" type="xs:NMTOKEN" use="required"></xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>

=== olixva/LenguajeMarcas_XML/xml + xsd/ejemplo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejemplo1.xsd">
    <tarea posibles_ejecutores="48843818y" estado="Finalizada" fecha="20 de febrero de 2011">
    fechaLimite="1 de marzo de 2011"> Preparar ejercicios de DTDs <ordenante dni="48843818y"></ordenante>
    </tarea>

    <tarea posibles_ejecutores="48843818y 48843817y" estado="Finalizada"
        fecha="20 de febrero de 2011"
        fechaLimite="1 de marzo de 2011"> Borrar ejercicios de DTDs <ordenante dni="48843818y"></ordenante>
    <ordenante
            dni="48843817y"></ordenante>
    </tarea>

    <tarea posibles_ejecutores="48843817y" estado="iniciada"> Aprobar examen <ordenante
            dni="48843817y"></ordenante>
    </tarea>

    <tarea posibles_ejecutores="48843818y" estado="No_iniciada"> fechaLimite="1 de marzo de 2011"
    Actualizar ejercicios de DTDs <ordenante dni="48843818y"></ordenante>
    </tarea>

    <tarea posibles_ejecutores="48843818y" estado="Finalizada" fecha="20 de febrero de 2011">
        Crear
        ejercicios de DTDs </tarea>


    <persona dni="48843818y">Antonio López Gomariz</persona>
    <persona dni="4884383y">Rogelio Marín Gutiérrez</persona>
    <persona dni="48832818y">Marcos Calero Gutiérrez</persona>
    <persona dni="48844568y">Lucia Burguillos Lopez</persona>
    <persona dni="44543818y">Daniel Oliva Cantero</persona>
</todoList>
