=== olixva/LenguajeMarcas_XML/xml + xsd/people.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definición del elemento principal "people" -->
  <xs:element name="people">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">

          <xs:element name="man">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="dni" type="xs:ID" />
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>

          <xs:element name="woman">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="dni" type="xs:ID" />
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>


          <xs:element name="man1">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="dni1">
                  <xs:simpleType>
                    <xs:restriction base="xs:ID">
                      <xs:pattern value="[A-Za-z]{1}[0-9]{8}" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="man2">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="dni2">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:pattern value="[0-9]{8}[A-Za-z]{1}" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="torero">
            <xs:complexType>
              <xs:simpleContent>
                <xs:extension base="xs:string">
                  <xs:attribute name="mote" type="xs:string" />
                </xs:extension>
              </xs:simpleContent>
            </xs:complexType>
          </xs:element>

        </xs:choice>


      </xs:sequence>
    </xs:complexType>

    <xs:unique name="Man2UniqueDNI2">
      <xs:selector xpath="man2" />
      <xs:field xpath="dni2" />
    </xs:unique>

    <xs:unique name="toreroUnicos">
      <xs:selector xpath="torero" />
      <xs:field xpath="@mote" /><!-- los atributos se identifican comenzando con @ -->
    </xs:unique>

  </xs:element>
</xs:schema>

=== olixva/LenguajeMarcas_XML/xml + xsd/people.xml
<?xml version="1.0" encoding="UTF-8"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="people.xsd">

<!-- Ejemplos para conseguir que NO se puedan repetir ciertos valores en el fichero xml -->

<!-- Lo más simple, usando atributos tipo ID bloqueará repticiones de los valores de ese atributo -->
<!-- Pero esos valores NO pueden empezar por un número, por la propia dfinición del tipo ID -->
<!-- OJO: XML es case sensitive, por lo que los dni's de Eloy y Elsa son distintos -->

<man dni="z12345678">Eloy</man>
<woman dni="Z123678">Elsa</woman>

<man1>
<nombre>Javier</nombre>
<dni1>S12343219</dni1>
</man1>

<man1>
<nombre>Jaime</nombre>
<!-- este valor ya existe, por lo que no sería válido <dni1>S12343219</dni1> -->
<dni1>S12343001</dni1>
</man1>

<!-- Vamos ahora a conseguir que cualquier cadena string consiga ser única -->
<!-- para ello usaremos un elemento <dni2> definido en <man2> que se use del tipo 12345678Z, empezando por número -->
<!-- en este caso usamos la  clausula de definición xs:unique, que se ha de definir en el elemento  PADRE padre de aquellos que queremos que sean únicos. -->
<!-- para este ejemplo de personas, queremos que los <man2> sean únicos en el <people>, por lo que la clausula 
     xs:unique la declaramos al final de la definción del elemento <people>. -->

<man2>
<nombre>Ginés</nombre>
<dni2>23232345T</dni2>
</man2>

<man2>
<nombre>Ginés</nombre>
 <!-- este elemento NO VALIDA por estar reètido   <dni2>23232345T</dni2>    -->
<dni2>33332345K</dni2>
</man2>


<!-- hagamos ahora que el elemnto <torero> sea único pero por un atributo "mote" que podrá tener cualquier contenido-->

<torero mote="EL JULI">Julio Aparicio</torero>
<torero mote="EL YIYO">Joselito</torero>
<torero mote="CÚCHARES">Francisco Arjona</torero>
<torero mote="PEPÍN JIMÉNEZ">José Jiménez Alcázar</torero>
<torero mote="EL JULI1">Julio UUUUAparicio</torero>



</people>
