=== olixva/LenguajeMarcas_XML/xml + xsd/examen09-02-AO/ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Elemento principal "pagos"-->
    <xs:element name="pagos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pago" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" maxOccurs="3" type="xs:string" default="A" />

                            <xs:element name="fechaNacimiento">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">

                                            <xs:attribute name="edad" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="16" />
                                                        <xs:maxInclusive value="24" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>

                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="hora" maxOccurs="unbounded" type="xs:time" />
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:fractionDigits value="2" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="cantidad" type="xs:integer" fixed="678" />
                            <xs:element name="pagado" minOccurs="0" type="xs:boolean"
                                default="false" />

                        </xs:sequence>

                        <xs:attribute name="dni" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{8}[A-Za-z]{1}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== olixva/LenguajeMarcas_XML/xml + xsd/examen09-02-AO/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej1.xsd">
    <pago dni="54643432Q">
        <nombre>Javier Toledano</nombre>
        <fechaNacimiento edad="19">1979-02-04</fechaNacimiento>
        <hora>23:55:15</hora>
        <hora>23:55:15</hora>
        <precio>123.56</precio>
        <cantidad>678</cantidad>
        <pagado>true</pagado>
    </pago>
</pagos>
