=== olixva/LenguajeMarcas_XML/xml+dtd/controlPrueba/controlPrueba2.dtd
<!ELEMENT mezclas_de_colores (mezcla)+>
    <!ELEMENT mezcla (color)+>
        <!ATTLIST mezcla resultado CDATA #REQUIRED>
    <!ELEMENT color (#PCDATA)>

=== olixva/LenguajeMarcas_XML/xml+dtd/controlPrueba/controlPrueba2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mezclas_de_colores SYSTEM "controlPrueba2.dtd">

<mezclas_de_colores>
    <mezcla resultado="naranja">
        <color>rojo</color>
        <color>amarillo</color>
    </mezcla>
    <mezcla resultado="gris">
        <color>negro</color>
        <color>blanco</color>
    </mezcla>
    <mezcla resultado="verde claro">
        <color>amarillo</color>
        <color>azul</color>
        <color>blanco</color>
    </mezcla>
</mezclas_de_colores>
